import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className={'grid place-items-center h-screen py-2'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className="w-6/12 ">
       <div className=' text-pink-500 text-3xl font-bold ' >urls</div>
       <div>when</div>
       <div>the shorter hi </div>
       <div>
        <input type="text" />
       </div>
       <div>
        the better
       </div>
       <button className='bg-pink-500 rounded '>Shorten</button>
     </div>
      
    </div>
  )
}

export default Home
